//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sebrae.Academico.SQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BasicScriptsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicScriptsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sebrae.Academico.SQL.Properties.BasicScriptsResources", typeof(BasicScriptsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Left INT = (#EXPRESSAO#);
        ///
        ///UPDATE
        ///    Table_A
        ///SET
        ///    Table_A.QT_Left = Table_A.QT_Left + 2
        ///FROM
        ///    TB_Pagina AS Table_A
        ///WHERE
        ///    Table_A.QT_Left &gt;= (@Left + 1)
        ///
        ///UPDATE
        ///    Table_A
        ///SET
        ///    Table_A.QT_Right = Table_A.QT_Right + 2
        ///FROM
        ///    TB_Pagina AS Table_A
        ///WHERE
        ///    Table_A.QT_Right &gt;= @Left.
        /// </summary>
        internal static string AdicionarPaginaScript {
            get {
                return ResourceManager.GetString("AdicionarPaginaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @NAME NVARCHAR(MAX) = (SELECT TOP 1 NAME FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;#SCRIPT_NAME#&apos;) AND TYPE IN (N&apos;FN&apos;, N&apos;IF&apos;, N&apos;TF&apos;));
        ///DECLARE @DROP_COMMAND NVARCHAR(MAX) = &apos;DROP FUNCTION &apos; + @NAME;
        ///IF @NAME IS NOT NULL BEGIN EXECUTE sp_executesql @DROP_COMMAND END
        ///GO
        ///
        ///
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///.
        /// </summary>
        internal static string PreFunctionScript {
            get {
                return ResourceManager.GetString("PreFunctionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @NAME NVARCHAR(MAX) = (SELECT TOP 1 NAME FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;#SCRIPT_NAME#&apos;) AND TYPE IN ( N&apos;P&apos;, N&apos;PC&apos; ));
        ///DECLARE @DROP_COMMAND NVARCHAR(MAX) = &apos;DROP PROCEDURE &apos; + @NAME;
        ///IF @NAME IS NOT NULL BEGIN EXECUTE sp_executesql @DROP_COMMAND END
        ///GO
        ///
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///.
        /// </summary>
        internal static string PreProcedureScript {
            get {
                return ResourceManager.GetString("PreProcedureScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CONSTRAINT_NAME VARCHAR(255) = 
        ///	(
        ///		SELECT C.CONSTRAINT_NAME
        ///		FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
        ///		WHERE FK.TABLE_NAME = &apos;#TABLE_NAME#&apos; AND CU.COLUMN_NAME = &apos;#COLUMN_NAME#&apos;
        ///	)
        ///
        ///EXEC (&apos;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RemoveForeignKeyScript {
            get {
                return ResourceManager.GetString("RemoveForeignKeyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CONSTRAINT_NAME VARCHAR(255) = 
        ///	(
        ///		SELECT CONSTRAINT_NAME
        ///		FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        ///		WHERE TABLE_NAME LIKE &apos;#TABLE_NAME#&apos; AND CONSTRAINT_TYPE LIKE &apos;PRIMARY KEY&apos;
        ///	)
        ///
        ///EXEC (&apos;ALTER TABLE #TABLE_NAME# DROP CONSTRAINT &apos; + @CONSTRAINT_NAME).
        /// </summary>
        internal static string RemovePrimaryKeyScript {
            get {
                return ResourceManager.GetString("RemovePrimaryKeyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Left INT = (#EXPRESSAO#);
        ///
        ///UPDATE
        ///    Table_A
        ///SET
        ///    Table_A.QT_Left = Table_A.QT_Left - 2
        ///FROM
        ///    TB_Pagina AS Table_A
        ///WHERE
        ///    Table_A.QT_Left &gt;= (@Left + 1)
        ///
        ///UPDATE
        ///    Table_A
        ///SET
        ///    Table_A.QT_Right = Table_A.QT_Right - 2
        ///FROM
        ///    TB_Pagina AS Table_A
        ///WHERE
        ///    Table_A.QT_Right &gt;= @Left.
        /// </summary>
        internal static string RemoverPaginaScript {
            get {
                return ResourceManager.GetString("RemoverPaginaScript", resourceCulture);
            }
        }
    }
}
