//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sebrae.Academico.SQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts_2824 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts_2824() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sebrae.Academico.SQL.Properties.Scripts_2824", typeof(Scripts_2824).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ER
        ///SET ER.ID_Cargo = UC.ID_Cargo
        ///FROM TB_EtapaResposta ER
        ///INNER JOIN TB_ProcessoResposta PR ON ER.ID_ProcessoResposta = PR.ID_ProcessoResposta
        ///INNER JOIN TB_UsuarioCargo UC ON UC.ID_UsuarioCargo = PR.ID_UsuarioCargo
        ///WHERE PR.ID_UsuarioCargo IS NOT NULL.
        /// </summary>
        public static string MigrarUsuarioCargoEmEtapaResposta {
            get {
                return ResourceManager.GetString("MigrarUsuarioCargoEmEtapaResposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CT INT = 1
        ///DECLARE @ID_Cargo INT
        ///DECLARE @ID_CargoPai INT
        ///DECLARE @ID_Cargo_New INT
        ///DECLARE @ID_CargoPai_New INT
        ///
        ///WHILE @CT &lt;= (SELECT COUNT(ID_Cargo) FROM TB_Cargo)
        ///BEGIN
        ///	DECLARE @Cargos TABLE(ID_Cargo INT, ID_CargoPai INT NULL);
        ///	DELETE FROM @Cargos;
        ///	INSERT INTO @Cargos (ID_Cargo, ID_CargoPai) SELECT TOP(@CT) ID_Cargo, ID_CargoPai FROM TB_Cargo
        ///
        ///	SET @ID_Cargo = (SELECT TOP(1) ID_Cargo FROM @Cargos ORDER BY ID_Cargo DESC)
        ///	SET @ID_CargoPai = (SELECT TOP(1) ID_CargoPai FROM @Cargos  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RecriarIds {
            get {
                return ResourceManager.GetString("RecriarIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* SCRIPT GERADO USANDO O SQLSERVER MANAGEMENT STUDIO EXPRESS */
        ///
        ///
        ///SET QUOTED_IDENTIFIER ON
        ///SET ARITHABORT ON
        ///SET NUMERIC_ROUNDABORT OFF
        ///SET CONCAT_NULL_YIELDS_NULL ON
        ///SET ANSI_NULLS ON
        ///SET ANSI_PADDING ON
        ///SET ANSI_WARNINGS ON
        ///
        ///
        ///GO
        ///ALTER TABLE dbo.TB_Cargo
        ///	DROP CONSTRAINT FK_Cargo_UF
        ///GO
        ///ALTER TABLE dbo.TB_UF SET (LOCK_ESCALATION = TABLE)
        ///GO
        ///
        ///
        ///GO
        ///ALTER TABLE dbo.TB_Cargo
        ///	DROP CONSTRAINT DF_TB_Cargo_IN_Ativo
        ///GO
        ///ALTER TABLE dbo.TB_Cargo
        ///	DROP CONSTRAINT DF_TB_Cargo_ID_UF
        ///GO
        ///CREATE  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RecriarTabelaSemIdentity {
            get {
                return ResourceManager.GetString("RecriarTabelaSemIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CONSTRAINT_NAME VARCHAR(255) = 
        ///	(
        ///		SELECT C.CONSTRAINT_NAME
        ///		FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
        ///		WHERE FK.TABLE_NAME = &apos;TB_UsuarioCargo&apos; AND CU.COLUMN_NAME = &apos;ID_Cargo&apos;
        ///	)
        ///
        ///EXEC (&apos;ALT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RemoverConstaintUsuarioCargo {
            get {
                return ResourceManager.GetString("RemoverConstaintUsuarioCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CONSTRAINT_NAME VARCHAR(255) = 
        ///	(
        ///		SELECT CONSTRAINT_NAME
        ///		FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
        ///		WHERE TABLE_NAME LIKE &apos;TB_Cargo&apos; AND CONSTRAINT_TYPE LIKE &apos;PRIMARY KEY&apos;
        ///	)
        ///
        ///EXEC (&apos;ALTER TABLE TB_Cargo DROP CONSTRAINT &apos; + @CONSTRAINT_NAME).
        /// </summary>
        public static string RemoverConstraintCargo {
            get {
                return ResourceManager.GetString("RemoverConstraintCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CONSTRAINT_NAME VARCHAR(255) = 
        ///	(
        ///		SELECT C.CONSTRAINT_NAME
        ///		FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
        ///		WHERE FK.TABLE_NAME = &apos;TB_Cargo&apos; AND CU.COLUMN_NAME = &apos;ID_CargoPai&apos;
        ///	)
        ///
        ///EXEC (&apos;ALTER T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RemoverConstraintCargoPai {
            get {
                return ResourceManager.GetString("RemoverConstraintCargoPai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CONSTRAINT_NAME VARCHAR(255) = 
        ///	(
        ///		SELECT C.CONSTRAINT_NAME
        ///		FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
        ///		INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
        ///		WHERE FK.TABLE_NAME = &apos;TB_UsuarioCargo&apos; AND CU.COLUMN_NAME = &apos;ID_UF&apos;
        ///	)
        ///
        ///EXEC (&apos;ALTER  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RemoverConstraintUsuarioCargoUf {
            get {
                return ResourceManager.GetString("RemoverConstraintUsuarioCargoUf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO
        ///
        ///ALTER TRIGGER [dbo].[TR_TB_Cargo_Update] ON [dbo].[TB_Cargo] AFTER UPDATE AS SET NOCOUNT ON
        ///INSERT INTO HT_Cargo
        ///	(ID_Cargo, NM_Cargo, VL_TipoCargo, ID_CargoPai, IN_RegistroExcluido, DT_EventoTrigger)
        ///SELECT
        ///	ID_Cargo, NM_Cargo, VL_TipoCargo, ID_CargoPai, &apos;0&apos;, GETDATE()
        ///	FROM Deleted
        ///
        ///GO
        ///
        ///ALTER TRIGGER [dbo].[TR_TB_Cargo_Delete] ON [dbo].[TB_Cargo] FOR DELETE AS SET NOCOUNT ON
        ///INSERT INTO HT_Cargo
        ///	(ID_Cargo, NM_Cargo, VL_TipoCargo, ID_CargoPai, IN_RegistroExcluido, DT_EventoTrigger)
        ///SELEC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RollbackTriggersCargo {
            get {
                return ResourceManager.GetString("RollbackTriggersCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO
        ///
        ///DROP TRIGGER [dbo].[TR_TB_UsuarioCargo_Delete]
        ///
        ///GO
        ///
        ///CREATE TRIGGER [dbo].[TR_TB_UsuarioCargo_Delete_copy]
        ///ON [dbo].[TB_UsuarioCargo]
        ///AFTER DELETE
        ///AS
        ///SET NOCOUNT ON
        ///INSERT INTO HT_UsuarioCargo
        ///	(ID_UsuarioCargo, ID_Usuario, ID_Cargo, IN_RegistroExcluido, DT_EventoTrigger)
        ///SELECT
        ///	ID_UsuarioCargo, ID_Usuario, ID_Cargo, &apos;1&apos;, GETDATE()
        ///	FROM Deleted
        ///GO
        ///
        ///DROP TRIGGER [dbo].[TR_TB_UsuarioCargo_Update]
        ///
        ///GO
        ///
        ///CREATE TRIGGER [dbo].[TR_TB_UsuarioCargo_Update_copy]
        ///ON [dbo].[TB_UsuarioCargo]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RollbackTriggersUsuarioCargo {
            get {
                return ResourceManager.GetString("RollbackTriggersUsuarioCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO
        ///
        ///ALTER TRIGGER [dbo].[TR_TB_Cargo_Update] ON [dbo].[TB_Cargo] AFTER UPDATE AS SET NOCOUNT ON
        ///INSERT INTO HT_Cargo
        ///	(ID_Cargo, NM_Cargo, VL_TipoCargo, ID_CargoPai, IN_Ativo, VL_Order, IN_RegistroExcluido, DT_EventoTrigger)
        ///SELECT
        ///	ID_Cargo, NM_Cargo, VL_TipoCargo, ID_CargoPai, IN_Ativo, VL_Order, &apos;0&apos;, GETDATE()
        ///	FROM Deleted
        ///
        ///GO
        ///
        ///ALTER TRIGGER [dbo].[TR_TB_Cargo_Delete] ON [dbo].[TB_Cargo] FOR DELETE AS SET NOCOUNT ON
        ///INSERT INTO HT_Cargo
        ///	(ID_Cargo, NM_Cargo, VL_TipoCargo, ID_CargoPai, IN_At [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TriggersCargo {
            get {
                return ResourceManager.GetString("TriggersCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO
        ///
        ///DROP TRIGGER [dbo].[TR_TB_UsuarioCargo_Delete_copy]
        ///
        ///GO
        ///
        ///CREATE TRIGGER [dbo].[TR_TB_UsuarioCargo_Delete]
        ///ON [dbo].[TB_UsuarioCargo]
        ///AFTER DELETE
        ///AS
        ///SET NOCOUNT ON
        ///INSERT INTO HT_UsuarioCargo
        ///	(ID_UsuarioCargo, ID_Usuario, ID_Cargo, IN_RegistroExcluido, DT_EventoTrigger)
        ///SELECT
        ///	ID_UsuarioCargo, ID_Usuario, ID_Cargo, &apos;1&apos;, GETDATE()
        ///	FROM Deleted
        ///GO
        ///
        ///DROP TRIGGER [dbo].[TR_TB_UsuarioCargo_Update_copy]
        ///
        ///GO
        ///
        ///CREATE TRIGGER [dbo].[TR_TB_UsuarioCargo_Update]
        ///ON [dbo].[TB_UsuarioCargo]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TriggersUsuarioCargo {
            get {
                return ResourceManager.GetString("TriggersUsuarioCargo", resourceCulture);
            }
        }
    }
}
