//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sebrae.Academico.WebForms.Cadastros.MonitoramentoIndicadores {
    
    
    public partial class Editar {
        
        /// <summary>
        /// lblAno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAno;
        
        /// <summary>
        /// UcHelperTooltip1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip1;
        
        /// <summary>
        /// txtAno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtAno;
        
        /// <summary>
        /// pnlMonitoramentoIndicador control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlMonitoramentoIndicador;
        
        /// <summary>
        /// lblColaboradoresPactuamMetaDesenvolvimentoPADI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblColaboradoresPactuamMetaDesenvolvimentoPADI;
        
        /// <summary>
        /// UcHelperTooltip2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip2;
        
        /// <summary>
        /// txtColaboradoresPactuamMetaDesenvolvimentoPADI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtColaboradoresPactuamMetaDesenvolvimentoPADI;
        
        /// <summary>
        /// lblEficaciaDosProgramasEducacionaisPortifolioUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEficaciaDosProgramasEducacionaisPortifolioUC;
        
        /// <summary>
        /// UcHelperTooltip3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip3;
        
        /// <summary>
        /// txtEficaciaDosProgramasEducacionaisPortifolioUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtEficaciaDosProgramasEducacionaisPortifolioUC;
        
        /// <summary>
        /// lblEficaciaDosProgramasAcademicos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEficaciaDosProgramasAcademicos;
        
        /// <summary>
        /// UcHelperTooltip4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip4;
        
        /// <summary>
        /// txtEficaciaDosProgramasAcademicos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtEficaciaDosProgramasAcademicos;
        
        /// <summary>
        /// lblAcoesDeGestaoDoConhecimentoRegistradasNoPADI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAcoesDeGestaoDoConhecimentoRegistradasNoPADI;
        
        /// <summary>
        /// UcHelperTooltip5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip5;
        
        /// <summary>
        /// txtAcoesDeGestaoDoConhecimentoRegistradasNoPADI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtAcoesDeGestaoDoConhecimentoRegistradasNoPADI;
        
        /// <summary>
        /// lblProducaoDeConteudoNaPlataformaSaberCrescimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProducaoDeConteudoNaPlataformaSaberCrescimento;
        
        /// <summary>
        /// UcHelperTooltip6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip6;
        
        /// <summary>
        /// txtProducaoDeConteudoNaPlataformaSaberCrescimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtProducaoDeConteudoNaPlataformaSaberCrescimento;
        
        /// <summary>
        /// lblColaboradoresCertificadosDoSistemaSebraeUniversoExcetoSP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblColaboradoresCertificadosDoSistemaSebraeUniversoExcetoSP;
        
        /// <summary>
        /// UcHelperTooltip7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip7;
        
        /// <summary>
        /// txtColaboradoresCertificadosDoSistemaSebraeUniversoExcetoSP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtColaboradoresCertificadosDoSistemaSebraeUniversoExcetoSP;
        
        /// <summary>
        /// lblColaboradoresCertificadosDoSistemaSebraeInscritos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblColaboradoresCertificadosDoSistemaSebraeInscritos;
        
        /// <summary>
        /// UcHelperTooltip8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip8;
        
        /// <summary>
        /// txtColaboradoresCertificadosDoSistemaSebraeInscritos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtColaboradoresCertificadosDoSistemaSebraeInscritos;
        
        /// <summary>
        /// lblColaboradoresCertificadosSebraeNA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblColaboradoresCertificadosSebraeNA;
        
        /// <summary>
        /// UcHelperTooltip9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip9;
        
        /// <summary>
        /// txtColaboradoresCertificadosSebraeNA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtColaboradoresCertificadosSebraeNA;
        
        /// <summary>
        /// lblCapacitacoesMetodologicasCredenciados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCapacitacoesMetodologicasCredenciados;
        
        /// <summary>
        /// UcHelperTooltip10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip10;
        
        /// <summary>
        /// txtCapacitacoesMetodologicasCredenciados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCapacitacoesMetodologicasCredenciados;
        
        /// <summary>
        /// lblRelacaoFolhaPagamentoSistemaSebrae control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblRelacaoFolhaPagamentoSistemaSebrae;
        
        /// <summary>
        /// UcHelperTooltip11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip11;
        
        /// <summary>
        /// txtRelacaoFolhaPagamentoSistemaSebrae control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRelacaoFolhaPagamentoSistemaSebrae;
        
        /// <summary>
        /// lblPercentualExecucaoOrcamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPercentualExecucaoOrcamento;
        
        /// <summary>
        /// UcHelperTooltip12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip12;
        
        /// <summary>
        /// txtPercentualExecucaoOrcamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPercentualExecucaoOrcamento;
        
        /// <summary>
        /// lblExecutado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblExecutado;
        
        /// <summary>
        /// UcHelperTooltip13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip13;
        
        /// <summary>
        /// txtExecutado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtExecutado;
        
        /// <summary>
        /// lblExecucaoPorcentagem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblExecucaoPorcentagem;
        
        /// <summary>
        /// UcHelperTooltip14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucHelperTooltip UcHelperTooltip14;
        
        /// <summary>
        /// txtExecucaoPorcentagem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtExecucaoPorcentagem;
        
        /// <summary>
        /// btnSalvar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSalvar;
        
        /// <summary>
        /// btnCancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCancelar;
    }
}
