DECLARE @CONSTRAINT_NAME VARCHAR(255) = 
	(
		SELECT CONSTRAINT_NAME
		FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
		WHERE TABLE_NAME LIKE '#TABLE_NAME#' AND CONSTRAINT_TYPE LIKE 'PRIMARY KEY'
	)

EXEC ('ALTER TABLE #TABLE_NAME# DROP CONSTRAINT ' + @CONSTRAINT_NAME)