//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sebrae.Academico.BP.solTokenService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sol.sebrae.com.br/ServiceSGUS/tokenws", ConfigurationName="solTokenService.TokenWS")]
    public interface TokenWS {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Sebrae.Academico.BP.solTokenService.gerarTokenResponse gerarToken(Sebrae.Academico.BP.solTokenService.gerarTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gerarTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gerarToken", Namespace="http://sol.sebrae.com.br/ServiceSGUS/tokenws", Order=0)]
        public Sebrae.Academico.BP.solTokenService.gerarTokenRequestBody Body;
        
        public gerarTokenRequest() {
        }
        
        public gerarTokenRequest(Sebrae.Academico.BP.solTokenService.gerarTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class gerarTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public gerarTokenRequestBody() {
        }
        
        public gerarTokenRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gerarTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gerarTokenResponse", Namespace="http://sol.sebrae.com.br/ServiceSGUS/tokenws", Order=0)]
        public Sebrae.Academico.BP.solTokenService.gerarTokenResponseBody Body;
        
        public gerarTokenResponse() {
        }
        
        public gerarTokenResponse(Sebrae.Academico.BP.solTokenService.gerarTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class gerarTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public gerarTokenResponseBody() {
        }
        
        public gerarTokenResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TokenWSChannel : Sebrae.Academico.BP.solTokenService.TokenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenWSClient : System.ServiceModel.ClientBase<Sebrae.Academico.BP.solTokenService.TokenWS>, Sebrae.Academico.BP.solTokenService.TokenWS {
        
        public TokenWSClient() {
        }
        
        public TokenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sebrae.Academico.BP.solTokenService.gerarTokenResponse Sebrae.Academico.BP.solTokenService.TokenWS.gerarToken(Sebrae.Academico.BP.solTokenService.gerarTokenRequest request) {
            return base.Channel.gerarToken(request);
        }
        
        public string gerarToken(string arg0, string arg1) {
            Sebrae.Academico.BP.solTokenService.gerarTokenRequest inValue = new Sebrae.Academico.BP.solTokenService.gerarTokenRequest();
            inValue.Body = new Sebrae.Academico.BP.solTokenService.gerarTokenRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Sebrae.Academico.BP.solTokenService.gerarTokenResponse retVal = ((Sebrae.Academico.BP.solTokenService.TokenWS)(this)).gerarToken(inValue);
            return retVal.Body.@return;
        }
    }
}
