namespace Sebrae.Academico.Dominio.Enumeracao
{
    public enum enumConfiguracaoSistema
    {
        SMTPServer = 1,
        SMTPPorta = 2,
        SMTPUsuario = 3,
        SMTPSenha = 4,
        SMTPUsarSSL = 5,
        SMTPRemetente = 6,
        SMTPCodificacao = 7,
        EmailAdministrador = 8,
        RepositorioUpload = 9,
        EnderecoPortal = 10,
        EnderecoSGUS = 11,
        UrlWebService = 12,
        LimiteAlertaInscricaoOferta = 13,
        DiasSuspensaoAbandono = 14,
        EmailErroSistema = 15,
        DiasCancelamentoCurso = 16,
        SenhaUsuarioDefaultDrupal = 17,
        EmailErro = 18,
        CursosSimultaneos = 19,
        UsuarioSOAPPortal = 20,
        SenhaSOAPPortal = 21,
        UrlTrilha = 22,
        SenhaPadrao = 23,
        EnderecoArquivos = 24,
        SessionRestPortal = 25,
        CSRFRestPortal = 26,
        PathRestPortal = 27,
        UsuarioRestPortal = 28,
        PasswordRestPortal = 29,
        UrlRestPortal = 30,
        SignalR = 31,
        SMTPRemetenteNome = 32,
        IdFormacaoDeFormadores = 33,
        UrlSoapEf = 34,
        LoginWebServiceEf = 35,
        SenhaWebServiceEf = 36,
        RedemptionCodeServiceEf = 37,
        EnderecoPortal30 = 38,
        ComunidadeVirtual = 39,
        ChaveAcessoSAS = 40,
        UrlTrilhasPortal30 = 41,
        LinkAcessoVivencia = 42,
        IDFornecedorVivencia = 43,
        MoodleUrlMatricular = 44,
        MoodleUrlAtualizarStatus = 49,
        MapaPreviewURL = 45,
        UrlCredenciamento = 46,
        DashboardRedmine = 47,
        UrlConheciGame = 48
    }
}