//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sebrae.Academico.WebForms {
    
    
    public partial class Dashboard {
        
        /// <summary>
        /// txtDataInicial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDataInicial;
        
        /// <summary>
        /// txtDataFinal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDataFinal;
        
        /// <summary>
        /// cbxUf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cbxUf;
        
        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        
        /// <summary>
        /// btnProximoMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnProximoMenu;
        
        /// <summary>
        /// ucGraficoMatriculadosUF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucGraficoMatriculadosUF ucGraficoMatriculadosUF;
        
        /// <summary>
        /// ucGraficoTop5Cursos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucRelatorioTop5Cursos ucGraficoTop5Cursos;
        
        /// <summary>
        /// ucGraficoBaseConcluintesMatriculados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.dashboard.ucGraficoBaseConcluintesMatriculados ucGraficoBaseConcluintesMatriculados;
        
        /// <summary>
        /// ucGraficoBaseConcluintesMatriculados1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.dashboard.ucGraficoBaseConcluintesMatriculados ucGraficoBaseConcluintesMatriculados1;
        
        /// <summary>
        /// ucGraficoMatriculadosPorMes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.dashboard.ucGraficoMatriculadosPorMes ucGraficoMatriculadosPorMes;
        
        /// <summary>
        /// ucGraficoConcluintesEspacoOcupacionalEmpregados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.dashboard.ucGraficoConcluintesEspacoOcupacionalEmpregados ucGraficoConcluintesEspacoOcupacionalEmpregados;
        
        /// <summary>
        /// ucGraficoConcluintesExternos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.dashboard.ucGraficoConcluintesExternos ucGraficoConcluintesExternos;
        
        /// <summary>
        /// ucGraficoIndiceSatisfacaoGeral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucGraficoIndiceSatisfacaoGeral ucGraficoIndiceSatisfacaoGeral;
        
        /// <summary>
        /// ucGraficoIndiceSatisfacaoCredenciados control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sebrae.Academico.WebForms.UserControls.ucGraficoIndiceSatisfacaoCredenciados ucGraficoIndiceSatisfacaoCredenciados;
    }
}
